name: Laravel MySQL

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-tests-mysql:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: unittest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Copy .env.testing.example
        run: cp .env.testing.example .env.testing
      - name: Install Dependencies
        run: composer update
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: JWT Secret on .env
        run: php artisan jwt:secret
      - name: JWT Secret on .env.testing
        run: sed -i '/^JWT_SECRET=/d' .env.testing; echo "JWT_SECRET=$(php artisan jwt:secret --show)" >> .env.testing

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_USERNAME: root
          DB_PASSWORD: ""
          DB_DATABASE: unittest
          DB_HOST: 127.0.0.1
        run: vendor/bin/phpunit
